feat: 엔티티 sql 스키마 정의
petnager/petnager-server pull request #5
Opened 2024-01-07 10:10 UTC by kureung

## Issue

- close #3 

## ✨ 구현한 기능
- 엔티티 sql 스키마 정의

2024-01-07 10:40 UTC, wugawuga requested changes
고생하셨습니당

2024-01-07 10:40 UTC, wugawuga commented on src/main/resources/sql/schema/member.sql
> +)
파일마다 마지막 줄 개행 부탁드릴게요

2024-01-07 14:02 UTC, wugawuga approved these changes
LGTM~ 👍

2024-01-08 03:04 UTC, k0duck approved these changes
수고하셨습니다.

<img width="300" alt="image" src="https://github.com/petnager/petnager-server/assets/91456818/92853c64-fc87-4ccd-9842-7c1c81f8c943">

줄 개행 추가는 `feat`이 아닌 `style`이 적합할 것 같습니다!
그리고 이런 경우는 커밋을 쪼개지 않고 줄 개행 추가 하나의 커밋으로 정리하는게 좋지 않을까 싶은 생각이 드네요.🧐

2024-01-08 04:13 UTC, merged